<?php echo $this->render('header.phtml') ?>
<h1><?php echo $this->title ?></h1>
<form action="/user/update" method="post">
    <ul>
        <li><label>Old Password:
            <?php echo $this->formPassword('user[password]') ?>
        </label></li>
        <li><label>New Password:
            <?php echo $this->formPassword('user[password_new]') ?>
        </label></li>
        <li><label>New Password Confirmation:
            <?php echo $this->formPassword('user[password_confim]') ?>
        </label></li>
        <li><label>Email:
            <?php echo $this->formText('user[email]', $this->user->email) ?>
        </label></li>
        <li><label>Address:
            <?php echo $this->formText('user[address]', $this->user->address) ?>
        </label></li>
        <li><label>City:
            <?php echo $this->formText('user[city]', $this->user->city) ?>
        </label></li>
        <li><label>State:
        	<?php echo $this->formSelect('user[state]', $this->user->state, null, $this->states) ?>
        </label></li>
        <li><label>Zip Code:
            <?php echo $this->formText('user[zip_code]', $this->user->zip_code) ?>
        </label></li>
        <li><label>Country:
            <?php echo $this->formText('user[country]', $this->user->country) ?>
        </label></li>
    <ul>
    <?php echo $this->formHidden('user[id]', $this->user->id) ?>
    <?php echo $this->formSubmit('Update') ?>
</form>
<?php echo $this->render('footer.phtml') ?>