<?php echo $this->render('header.phtml') ?>
<h1><?php echo $this->user->name ?></h1>
<?php if (isset($this->session) &&
          isset($this->session->user_id) &&
          $this->user->id == $this->session->user_id) { ?>
<ul>
    <li>Balance: <?php echo $this->user->balance ?></li>
    <li>Address:<br/>
        <?php echo $this->user->address ?><br />
        <?php echo $this->user->city ?>,
        <?php echo $this->user->state ?>
        <?php echo $this->user->zip_code ?><br />
        <?php echo $this->user->country ?></li>
    <li>Email: <?php echo $this->user->email ?></li>
</ul>

<?php if ($this->items->exists()) { ?>
    <h2>Items</h2>
    <ul>
        <?php foreach($this->items as $item) { ?>
            <li>
                <a href="/items/show/<?php echo $item->id ?>"><?php echo $item->name ?></a>
            <?php if ($item->sold) { ?>
                SOLD
            <?php } ?>
            </li>
        <?php } ?>
    </ul>
<?php } ?>

<ul>
    <li><a href="/items/new">Post an Item</a></li>
    <li><a href="/user/edit/<?php echo $this->user->id ?>">Edit</a></li>
    <li><?php echo $this->render('_logout.phtml')?></li>
    <li><form action="/user/destroy" method="post">
        <?php echo $this->formHidden('user[id]', $this->user->id) ?>
        <?php echo $this->formSubmit('', 'Delete Account') ?>
    </form></li>
</ul>
<?php } ?>
<?php echo $this->render('footer.phtml') ?>