<?php echo $this->render('header.phtml'); ?>
<h1>Item Index</h1>
<p><a href="/items/new">Post a item</a></p>
<?php foreach($this->items as $item) { ?>
    <h2><a href="/items/show/<?php echo $item->id?>">
        <?php echo $item->name ?>
    </a></h2>
    <ul>
        <li><img src="/image/show/<?php echo $item->image_id ?>"></li>
        <li>Swapbucks: <?php echo $item->points ?></li>
        <li>Description: <?php echo $item->description ?></li>
        <li>Weight: <?php echo $item->weight ?></li>
    </ul>
    <?php if ($item->owner_id == $this->session->user_id) { ?>
        <ul>
            <li><a href="/items/edit/<?php echo $item->id ?>">Edit</a></li>
            <li><form action="/items/destroy" method="POST">
                <?php echo $this->formHidden('item[id]', $item->id) ?>
                <?php echo $this->formSubmit('destroy', 'Delete') ?>
            </form></li>
        </ul>
    <?php } ?>
<?php } ?>
<?php echo $this->render('footer.phtml'); ?>
