<?php echo $this->render('header.phtml') ?>
<?php require_once 'Tag.php'; ?>
<h1>Search Results</h1>
<?php foreach($this->items as $item) { ?>
    <h2><a href="/items/show/<?php echo $item->item_id?>">
        <?php echo $item->title ?>
    </a></h2>
    <ul>
        <li><img src="/image/show/<?php echo $item->image_id ?>"></li>
        <li>
            <?php foreach (Tag::parseTags($item->tag) as $tag) { ?>
                <a href="/tag/<?php echo $tag ?>"><?php echo $tag ?></a>
            <?php } ?>
        </li>
        <li><?php echo $item->description ?></li>
    </ul>
<?php } ?>
<?php echo $this->render('footer.phtml') ?>